[package]
name = "zec-rsp"
description = ""
version = "0.4.0"
edition = "2021"

[workspace]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
bincode = "1.3.3"
rsp-client-executor = { git = "https://github.com/succinctlabs/rsp.git", rev = "545ae85f21ba274b97ee8cb68b86acc5c3dd6b4a" }
# rsp-client-executor = { path = "../../../../rsp/crates/executor/client" }

ziskos = { git = "https://github.com/0xPolygonHermez/zisk.git", branch = "feature/modexp" }
# Local development
# ziskos = { path = "../../../../../zisk/ziskos/entrypoint" }

[patch."https://github.com/succinctlabs/kzg-rs"]
kzg-rs = { git = "https://github.com/0xPolygonHermez/zisk-patch-kzg.git", branch = "fix/bls" }
# kzg-rs = { path = "../../../../zisk-patch-kzg" }

[patch.crates-io]
ruint = { git = "https://github.com/0xPolygonHermez/zisk-patch-ruint.git", tag = "patch-1.17.0-zisk-0.13.1" }
sha2 = { git = "https://github.com/0xPolygonHermez/zisk-patch-hashes.git", branch = "fix/bls" }
sha3 = { git = "https://github.com/0xPolygonHermez/zisk-patch-hashes.git", tag = "patch-sha3-0.10.8-zisk-0.14.0" }
k256 = { git = "https://github.com/0xPolygonHermez/zisk-patch-elliptic-curves.git", branch = "fix/bls" }
bn = { git = "https://github.com/0xPolygonHermez/zisk-patch-bn.git", branch = "fix/bls", package = "substrate-bn" }
sp1_bls12_381 = { git = "https://github.com/0xPolygonHermez/zisk-patch-bls12-381.git", branch = "fix/bls" }
ark-bls12-381 = { git = "https://github.com/0xPolygonHermez/zisk-patch-ark-algebra.git", branch = "fix/bls" }
ark-ec = { git = "https://github.com/0xPolygonHermez/zisk-patch-ark-algebra.git", branch = "fix/bls" }
ark-ff = { git = "https://github.com/0xPolygonHermez/zisk-patch-ark-algebra.git", branch = "fix/bls" }
ark-bn254 = { git = "https://github.com/0xPolygonHermez/zisk-patch-ark-algebra.git", branch = "fix/bls" }
ark-serialize  = { git = "https://github.com/0xPolygonHermez/zisk-patch-ark-algebra.git", branch = "fix/bls" }
modexp = { git = "https://github.com/0xPolygonHermez/zisk-patch-modexp.git", branch = "zisk-patch/v1.2.0", package = "aurora-engine-modexp" }
# # Local development
# ruint = { path = "../../../../zisk-patch-ruint" }
# sha2 = { path = "../../../../zisk-patch-sha2/sha2" }
# sha3 = { path = "../../../../zisk-patch-sha3/sha3" }
# k256 = { path = "../../../../zisk-patch-k256/k256" }
# bn = { path = "../../../../zisk-patch-bn", package = "substrate-bn" }
# sp1_bls12_381 = { path = "../../../../zisk-patch-bls12-381" }
# ark-bls12-381 = { path = "../../../../zisk-patch-ark-algebra/curves/bls12_381" }
# ark-ec = { path = "../../../../zisk-patch-ark-algebra/ec" }
# ark-ff = { path = "../../../../zisk-patch-ark-algebra/ff" }
# ark-bn254 = { path = "../../../../zisk-patch-ark-algebra/curves/bn254" }
# ark-serialize = { path = "../../../../zisk-patch-ark-algebra/serialize" }
# modexp = { path = "../../../../zisk-patch-modexp/engine-modexp", package = "aurora-engine-modexp" }
